In [ ]:
import numpy as np
m1=np.matrix('1,2,3;4,5,6;7,8,9')
print(m1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
m2=np.matrix('1,2,3;4,5,6;7,8,9')
print(m2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
m3=np.matmul(m1,m2)
print(m3)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [ ]:
m4=np.identity(20,dtype=int)
print(m4)

[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]]


In [ ]:
m5=np.matrix('1,3,3;1,4,3;1,3,4')
print(m5)
m6=np.linalg.inv(m5)
m7=np.matmul(m5,m6)
print(m7)

[[1 3 3]
 [1 4 3]
 [1 3 4]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
m8=np.linalg.det(m5)
print(m8)

1.0


In [ ]:
m9=np.transpose(m5)
print(m9)

[[1 1 1]
 [3 4 3]
 [3 3 4]]
